"""initial schema

Revision ID: 37faf04de94a
Revises: 
Create Date: 2025-08-31 23:34:43.360067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37faf04de94a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imovel_codigo', sa.String(length=64), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CRIADA', 'EM_ANALISE', 'APROVADA', 'FINALIZADA', 'CANCELADA', name='status_transacao'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_imovel_codigo', 'transacao', ['imovel_codigo'], unique=False)
    op.create_index('ix_transacao_data_criacao', 'transacao', ['data_criacao'], unique=False)
    op.create_index('ix_transacao_status', 'transacao', ['status'], unique=False)
    op.create_table('comissao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transacao_id', sa.UUID(), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('valor_calculado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paga', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parte',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transacao_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('COMPRADOR', 'VENDEDOR', 'CORRETOR', name='tipo_parte'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parte')
    op.drop_table('comissao')
    op.drop_index('ix_transacao_status', table_name='transacao')
    op.drop_index('ix_transacao_data_criacao', table_name='transacao')
    op.drop_index('ix_imovel_codigo', table_name='transacao')
    op.drop_table('transacao')
    # ### end Alembic commands ###
